# Workflow modified from: https://mattsegal.dev/pytest-on-github-actions.html

name: Project Tests
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Eclipse SUMO
        run: |
          sudo apt-get install sumo sumo-tools sumo-doc
          ls ..
      - run: |
          export SUMO_HOME="$PWD/sumo"
          echo $SUMO_HOME
      - run: |
          export PYTHONPATH="$SUMO_HOME/tools:$PYTHONPATH"
          echo $PYTHONPATH
      - name: Test with pytest
        run: python -m unittest discover --verbose